### ISSUE TITLE
function bold() { [native code] }

### ISSUE THREAD

**Issue by zero-** [pric/termtable#1] opened 2015-12-21 18:10 UTC
I'm getting `function bold() { [native code] }` instead of column names. Values in each column are correct but column names give that.

I'm running Node v4.2.3 and installed v1.0.1 from npm.

**Comment by pric** [comment] 2015-12-21 19:27
Can you show me the snippet of code that is causing the error? Thanks

**Comment by pric** [comment] 2015-12-21 19:52
The issue is fixed with commit https://github.com/pric/termtable/commit/e33aabd76c8f4559f7a9b7ed9526411e06b90200. Thank you for reporting it!

**Closed by pric** 2015-12-21 19:52 UTC
